name: Build libaria2.so for Android (ARM64)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential autoconf libtool pkg-config \
          git cmake curl unzip automake

    - name: Install Android NDK
      run: |
        mkdir -p $HOME/android-ndk
        curl -o ndk.zip https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
        unzip ndk.zip -d $HOME/android-ndk
        export ANDROID_NDK_HOME=$HOME/android-ndk/android-ndk-r25c
        export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

    - name: Clone aria2 repository
      run: |
        git clone https://github.com/aria2/aria2.git
        cd aria2
        git submodule update --init --recursive

    - name: Configure and Build Aria2 for Android ARM64
      run: |
        cd aria2
        autoreconf -i
        ./configure --host=aarch64-linux-android \
          --without-ssl --without-libxml2 \
          --enable-static --disable-shared \
          --prefix=$PWD/build-android
        make -j$(nproc)
        make install

    - name: Upload libaria2.so artifact
      uses: actions/upload-artifact@v4
      with:
        name: libaria2-android-arm64
        path: aria2/build-android/lib/libaria2.so
