name: Build libaria2.so for Android (ARM64)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential autoconf libtool pkg-config \
          git cmake curl unzip

    - name: Install Android NDK
      run: |
        mkdir -p $HOME/android-ndk
        curl -o ndk.zip https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
        unzip ndk.zip -d $HOME/android-ndk
        export ANDROID_NDK_HOME=$HOME/android-ndk/android-ndk-r25c

    - name: Clone aria2 repository
      run: |
        git clone https://github.com/aria2/aria2.git
        cd aria2
        git submodule update --init --recursive

    - name: Configure CMake for Android ARM64
      run: |
        mkdir -p build-android
        cd build-android
        cmake ../aria2 \
          -DCMAKE_SYSTEM_NAME=Android \
          -DCMAKE_SYSTEM_VERSION=21 \
          -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
          -DCMAKE_ANDROID_NDK=$HOME/android-ndk/android-ndk-r25c \
          -DCMAKE_ANDROID_STL_TYPE=c++_static \
          -DCMAKE_BUILD_TYPE=Release

    - name: Build libaria2.so
      run: |
        cd build-android
        make -j$(nproc)

    - name: Upload libaria2.so artifact
      uses: actions/upload-artifact@v4
      with:
        name: libaria2-android-arm64
        path: build-android/src/.libs/libaria2.so
